# NumPy
## (Documentation)
### https://www.w3schools.com/python/numpy/default.asp

### Importing NumPy and checking version

In [9]:
import numpy as np

In [10]:
print(np.__version__)

1.26.4


### Creating Array and Checking Dimension, Type

In [11]:
arr0 = np.array(42)
#0D Array (above one)
arr1 = np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]) 
#1D Array (above one)
arr2 = np.array([[12,34,56], [78,90,123]]) #no of elements in each list should be same
#2D Array (above one)

print(type(arr0), type(arr1), type(arr2))
print(arr0, arr0.ndim)
print(arr1, arr1.ndim)
print(arr2, arr2.ndim)
#arr.ndim => dimension of that array

<class 'numpy.ndarray'> <class 'numpy.ndarray'> <class 'numpy.ndarray'>
42 0
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15] 1
[[ 12  34  56]
 [ 78  90 123]] 2


### Array Indexing, Slicing

In [12]:
print(arr1[2])
print(arr2[0, 1])
print(arr2[0, 0] + arr2[1, 0]) #12+78
#Negative Indexing i.e., we can use -ve values for indexing by counting from back side.
print(arr2[-1, 2])

#Slicing
print()
print(arr1)
print("Slicing from now on:")
print(arr1[2:5])
print(arr1[:6])
print(arr1[5:])

#Return every other element from index 1 to index 5:
print(arr1[0::2]) #slicing 1D array
print(arr2[0,0:3:2])

3
34
90
123

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Slicing from now on:
[3 4 5]
[1 2 3 4 5 6]
[ 6  7  8  9 10 11 12 13 14 15]
[ 1  3  5  7  9 11 13 15]
[12 56]


In [13]:
print(arr1.dtype) #datatype of an array
print(arr2.dtype)

int32
int32


# Numpy Random

In [15]:
from numpy import random

### What is a Random Number?

Random number does NOT mean a different number every time.
Random means something that can not be predicted logically.

Computers work on programs, and programs are definitive set of instructions. So it means there must be some algorithm to generate a random number as well.

If there is a program to generate random number it can be predicted, thus it is not truly random.

Random numbers generated through a generation algorithm are called   
##### Pseudo Random

-------------------------------------------------------------------

### Generate a random integer from 0 to 100:

In [28]:
x = random.randint(100)
print(x)

18


### Generate Random Float
Generates random float from 0 to 1

In [33]:
x = random.rand()
print(x)

0.9837791337649294
