In [16]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC

In [17]:
train_df = pd.read_csv('WDBC_Train.csv')
valid_df = pd.read_csv('WDBC_Validation.csv')
test_df = pd.read_csv('WDBC_Test.csv')

train_df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0          0       11.360         17.57           72.49      399.8   
1          1       21.610         22.28          144.40     1407.0   
2          0       13.150         15.34           85.31      538.9   
3          0        9.683         19.34           61.05      285.7   
4          1       21.560         22.39          142.00     1479.0   

   smoothness_mean  compactness_mean  concavity_mean  concave_points_mean  \
0          0.08858           0.05313         0.02783             0.021000   
1          0.11670           0.20870         0.28100             0.156200   
2          0.09384           0.08498         0.09293             0.034830   
3          0.08491           0.05030         0.02337             0.009615   
4          0.11100           0.11590         0.24390             0.138900   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.1601  ...         13.05          36.32            85.07   
1         0.2162  ...         26.23          28.74           172.00   
2         0.1822  ...         14.77          20.50            97.67   
3         0.1580  ...         10.93          25.59            69.10   
4         0.1726  ...         25.45          26.40           166.10   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0       521.3            0.1453            0.16220           0.1811   
1      2081.0            0.1502            0.57170           0.7053   
2       677.3            0.1478            0.22560           0.3009   
3       364.2            0.1199            0.09546           0.0935   
4      2027.0            0.1410            0.21130           0.4107   

   concave_points_worst  symmetry_worst  fractal_dimension_worst  
0               0.08698          0.2973                  0.07745  
1               0.24220          0.3828                  0.10070  
2               0.09722          0.3849                  0.08633  
3               0.03846          0.2552                  0.07920  
4               0.22160          0.2060                  0.07115  

[5 rows x 31 columns]

In [18]:
X_train, y_train = train_df.iloc[:, 1:], train_df.iloc[:, 0]
X_valid, y_valid = valid_df.iloc[:, 1:], valid_df.iloc[:, 0]
X_test, y_test = test_df.iloc[:, 1:], test_df.iloc[:, 0]

print('Train shape: ', X_train.shape)
print('Validation shape: ', X_valid.shape)
print('Test shape: ', X_test.shape)

Train shape:  (341, 30)
Validation shape:  (114, 30)
Test shape:  (114, 30)


### C = 1

In [19]:
rbf_svm = SVC(kernel='rbf', C=1.0, gamma='scale')
rbf_svm.fit(X_train, y_train)
y_valid_pred = rbf_svm.predict(X_valid)
y_test_pred = rbf_svm.predict(X_test)

print("---------Validation-----------")

cm = confusion_matrix(y_valid, y_valid_pred)
acc = accuracy_score(y_valid, y_valid_pred)
precision = precision_score(y_valid, y_valid_pred)
recall = recall_score(y_valid, y_valid_pred)
f1 = f1_score(y_valid, y_valid_pred)

print(f"Accuracy on Validation: {acc:.4f}")
print("Confusion Matrix:")
print(cm)
print(f"Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1:.4f}\n")


print("---------Test-----------")


cm1 = confusion_matrix(y_test_pred, y_test)
acc1 = accuracy_score(y_test_pred, y_test)
precision1 = precision_score(y_test_pred, y_test)
recall1 = recall_score(y_test_pred, y_test)
f11 = f1_score(y_test_pred, y_test)

print(f"Accuracy on Test: {acc1:.4f}")
print("Confusion Matrix:")
print(cm1)
print(f"Precision: {precision1:.4f}, Recall: {recall1:.4f}, F1-score: {f11:.4f}\n")

---------Validation-----------
Accuracy on Validation: 0.8509
Confusion Matrix:
[[70  1]
 [16 27]]
Precision: 0.9643, Recall: 0.6279, F1-score: 0.7606

---------Test-----------
Accuracy on Test: 0.9298
Confusion Matrix:
[[71  7]
 [ 1 35]]
Precision: 0.8333, Recall: 0.9722, F1-score: 0.8974



### C = 0.01

In [20]:
rbf_svm = SVC(kernel='rbf', C=0.01, gamma='scale')
rbf_svm.fit(X_train, y_train)
y_valid_pred = rbf_svm.predict(X_valid)
y_test_pred = rbf_svm.predict(X_test)

print("---------Validation-----------")

cm = confusion_matrix(y_valid, y_valid_pred)
acc = accuracy_score(y_valid, y_valid_pred)
precision = precision_score(y_valid, y_valid_pred)
recall = recall_score(y_valid, y_valid_pred)
f1 = f1_score(y_valid, y_valid_pred)

print(f"Accuracy on Validation: {acc:.4f}")
print("Confusion Matrix:")
print(cm)
print(f"Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1:.4f}\n")


print("---------Test-----------")


cm1 = confusion_matrix(y_test_pred, y_test)
acc1 = accuracy_score(y_test_pred, y_test)
precision1 = precision_score(y_test_pred, y_test)
recall1 = recall_score(y_test_pred, y_test)
f11 = f1_score(y_test_pred, y_test)

print(f"Accuracy on Test: {acc1:.4f}")
print("Confusion Matrix:")
print(cm1)
print(f"Precision: {precision1:.4f}, Recall: {recall1:.4f}, F1-score: {f11:.4f}\n")

---------Validation-----------
Accuracy on Validation: 0.6754
Confusion Matrix:
[[71  0]
 [37  6]]
Precision: 1.0000, Recall: 0.1395, F1-score: 0.2449

---------Test-----------
Accuracy on Test: 0.6754
Confusion Matrix:
[[72 37]
 [ 0  5]]
Precision: 0.1190, Recall: 1.0000, F1-score: 0.2128



### C = 10

In [21]:
rbf_svm = SVC(kernel='rbf', C=10, gamma='scale')
rbf_svm.fit(X_train, y_train)
y_valid_pred = rbf_svm.predict(X_valid)
y_test_pred = rbf_svm.predict(X_test)

print("---------Validation-----------")

cm = confusion_matrix(y_valid, y_valid_pred)
acc = accuracy_score(y_valid, y_valid_pred)
precision = precision_score(y_valid, y_valid_pred)
recall = recall_score(y_valid, y_valid_pred)
f1 = f1_score(y_valid, y_valid_pred)

print(f"Accuracy on Validation: {acc:.4f}")
print("Confusion Matrix:")
print(cm)
print(f"Precision: {precision:.4f}, Recall: {recall:.4f}, F1-score: {f1:.4f}\n")


print("---------Test-----------")


cm1 = confusion_matrix(y_test_pred, y_test)
acc1 = accuracy_score(y_test_pred, y_test)
precision1 = precision_score(y_test_pred, y_test)
recall1 = recall_score(y_test_pred, y_test)
f11 = f1_score(y_test_pred, y_test)

print(f"Accuracy on Test: {acc1:.4f}")
print("Confusion Matrix:")
print(cm1)
print(f"Precision: {precision1:.4f}, Recall: {recall1:.4f}, F1-score: {f11:.4f}\n")

---------Validation-----------
Accuracy on Validation: 0.8860
Confusion Matrix:
[[70  1]
 [12 31]]
Precision: 0.9688, Recall: 0.7209, F1-score: 0.8267

---------Test-----------
Accuracy on Test: 0.9386
Confusion Matrix:
[[70  5]
 [ 2 37]]
Precision: 0.8810, Recall: 0.9487, F1-score: 0.9136

